spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
    url: jdbc:mariadb://localhost:3306/hibernate_examples
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
